import { ArrowDownRight, ArrowUpRight, Phone, Sparkles } from "lucide-react";
import ProblemForm from "../components/ProblemForm";
import HeroEnhanced from "../components/HeroEnhanced";
import FlowDiagram from "../components/FlowDiagrams";
import { catalogueTools, coreTools, microSaas } from "../components/microSaas";

export default function Home() {
  return <main>
    <header className="top"><a className="brand" href="#top">ЭЙ АЙ, <em>БОЛЬНО</em></a><div className="topRight"><span>МИКРОИНСТРУМЕНТЫ · 15</span><a href="https://t.me/bloodaman" target="_blank" rel="noreferrer">TELEGRAM ↗</a></div></header>
    <section className="hero" id="top">
      <div className="heroCopy"><p className="eyebrow"><span /> Каталог микроинструментов для малого бизнеса</p><h1>Бизнесу не нужна<br />ещё одна система.<br /><em>Ему больно</em> терять<span className="h1Tail"><br />одно и то же.</span></h1><div className="knot"><div className="knotFallback"><i /><i /><i /><i /></div><HeroEnhanced /></div><p className="heroText">Заявки тонут в чатах. Новичков учат по памяти. Смены передают на словах. Мы собираем заявки на микроинструменты, которые распутывают одну ручную операцию за раз.</p><a href="#form" className="button">Описать боль <ArrowDownRight size={18} /></a><a href="#details" className="buttonGhost">Смотреть каталог <ArrowDownRight size={18} /></a></div>
      <p className="heroFoot">СОБИРАЕМ ЗАЯВКИ НА РАЗРАБОТКУ<br />ОТВЕТИМ В ТЕЧЕНИЕ ДНЯ</p>
    </section>
    <section className="diagnosis"><p className="sectionNo">01 / ЧТО Я ВИЖУ У ВСЕХ</p><h2>Хаос не приходит<br />вдруг. Он <em>копится.</em></h2><div className="sceneGrid"><article><b>«Где вообще была эта заявка?»</b><p>Клиент написал в чат, менеджер ответил в личке, детали остались в голосовом. К вечеру никто не помнит, что обещали.</p></article><article><b>«Кто объяснит это новенькому?»</b><p>Сотрудник ушёл — инструкция ушла вместе с ним. Следующий учится на тех же ошибках, по кругу.</p></article><article><b>«А смене вообще сказали?»</b><p>Незакрытый заказ, остаток, конфликт с клиентом — об этом узнают тогда, когда исправлять уже дороже.</p></article></div><p className="diagnosisEnd">Не нужен монстр с внедрением на полгода, чтобы заткнуть одну дырявую операцию. Напишите мне, где у вас течёт, — я соберу под это маленький понятный инструмент.</p></section>
    <section className="solutions" id="solutions"><div className="solutionIntro"><p className="sectionNo">02 / ВОЗЬМУ В РАБОТУ ПЕРВЫМИ</p><h2>Начну с того,<br />что <em>болит каждый день.</em></h2></div><div>{coreTools.map((tool) => <article className="solution" key={tool.id}><span>{tool.num}</span><div><p className="solutionName">{tool.name}</p><h3>{tool.short?.title}</h3><p>{tool.short?.text}</p><div className="solutionCtas"><a href="#form">Разберите мой процесс <ArrowUpRight size={16} /></a><a href={`#${tool.id}`}>Что внутри <ArrowDownRight size={16} /></a></div></div></article>)}</div></section>
    <section className="catalogue" id="catalogue"><div><p className="sectionNo">03 / ОЧЕРЕДЬ</p><h2>Остальные боли<br />тоже <em>не обязаны</em><br />жить в таблицах.</h2><p className="catalogueHint">Каждая строка — отдельная секция ниже: реальная ситуация, боль, сценарий пилота и три шага работы.</p></div><div className="catalogueList">{catalogueTools.map((tool) => <a href={`#${tool.id}`} key={tool.id}><span>{tool.num}</span>{tool.name}<small>Собираю заявки <ArrowUpRight size={14} /></small></a>)}</div></section>
    <section className="details" id="details"><div className="detailsHead"><div><p className="sectionNo">04 / ВСЯ ОЧЕРЕДЬ ПО ПОЛКАМ</p><h2>Пятнадцать болей.<br />Ни одна <em>не выдумана.</em></h2></div><p>По каждой я расписал реальную ситуацию, одну конкретную боль, честный сценарий пилота и три шага работы. Это заявки на разработку, а не готовые сервисы: сначала проверяю, распутывается ли узел.</p></div><div className="caseList">{microSaas.map((tool) => <section className="case" id={tool.id} key={tool.id} aria-labelledby={`${tool.id}-title`}><header className="caseHead"><span className="caseNum">{tool.num}</span><div><p className="caseName">{tool.name}<span className="detailStatus">{tool.core ? "Возьму в работу первым" : "Собираю заявки"}</span></p><h3 id={`${tool.id}-title`}>{tool.title}</h3></div></header><div className="caseBody"><div><p className="caseLabel">КАК ЭТО ВЫГЛЯДИТ В ЖИЗНИ</p><p className="caseText">{tool.situation}</p><p className="caseLabel">ЧТО ИМЕННО БОЛИТ</p><p className="caseText caseBiz">{tool.bizPain}</p><p className="caseAudience">Кому это нужно: {tool.audience}</p></div><div className="caseFlow"><p className="caseLabel">ВХОД → ЧТО ДЕЛАЮ → ЧТО ВИДНО</p><FlowDiagram id={tool.id} /></div></div><div className="caseGrid"><div className="casePilot"><p className="caseLabel">ЧТО Я ПРОВЕРЮ В ПИЛОТЕ</p><p className="caseText">{tool.pilot}</p></div><div className="caseSteps"><p className="caseLabel">ТРИ ШАГА РАБОТЫ</p><ol>{tool.steps.map((step, index) => <li key={step.title}><span>{index + 1}</span><div><b>{step.title}</b><p>{step.text}</p></div></li>)}</ol></div></div><a className="button caseCta" href="#form">Написать про похожую боль <ArrowUpRight size={18} /></a></section>)}</div></section>
    <section className="process"><p className="sectionNo">05 / КАК Я РАБОТАЮ</p><div className="processTitle"><h2>Не обещаю<br />«подключу завтра».<br /><em>Сначала пойму.</em></h2><p>Это не коробка и не внедрение на полгода. Я беру процессы, которые повторяются каждый день и реально мешают работать.</p></div><ol><li><span>1</span><b>Вы пишете одну боль</b><p>Не «нужна автоматизация», а «заявка теряется между Telegram и менеджером».</p></li><li><span>2</span><b>Я отвечаю в течение дня</b><p>Спрошу, где процесс ломается, кто в нём участвует и какой результат вам нужен.</p></li><li><span>3</span><b>Я собираю сценарий пилота</b><p>Вы заранее видите, что будем проверять, какие данные понадобятся и чего в первой версии не будет.</p></li><li><span>4</span><b>Беру в работу самое повторяющееся</b><p>Без обещаний, которые нельзя сдержать: сначала условия — потом сроки.</p></li></ol></section>
    <section className="formSection" id="form"><div className="formLead"><p className="sectionNo">06 / ТЕПЕРЬ ВЫ</p><h2>Назовите одну<br />операцию, от которой<br /><em>уже болит.</em></h2><p>Не буду продавать вам систему на полгода внедрения. Сначала пойму, можно ли распутать именно ваш узел.</p><a className="contact" href="tel:+79037275131"><Phone size={18} /> +7 903 727-51-31</a><a className="contact" href="https://t.me/bloodaman" target="_blank" rel="noreferrer"><Sparkles size={18} /> @bloodaman в Telegram</a></div><ProblemForm /></section>
    <section className="faq"><p className="sectionNo">07 / ЧЕСТНЫЕ ОТВЕТЫ</p><details><summary>Это уже готовые сервисы?<span>+</span></summary><p>Нет. Я собираю заявки и первым делом беру в разработку процессы, которые повторяются чаще всего и обходятся дороже всего.</p></details><details><summary>Подключите к нашей CRM, 1С или Telegram?<span>+</span></summary><p>Скажу честно после разбора процесса: где реально подключиться, а где проще без этого. До технической оценки ничего не обещаю.</p></details><details><summary>Можно прислать базу клиентов или документы?<span>+</span></summary><p>Не через эту форму. На первом шаге достаточно описать процесс обычными словами — без баз, паролей и бумаг.</p></details><details><summary>Как быстро вы отвечаете?<span>+</span></summary><p>В течение дня. Пишу лично — без ботов и секретарей.</p></details></section>
    <footer><a className="brand" href="#top">ЭЙ АЙ, <em>БОЛЬНО</em></a><p>Один человек. Одна операция за раз.</p><a href="tel:+79037275131">+7 903 727-51-31</a></footer>
  </main>;
}
