import { ArrowDownRight, ArrowUpRight, Phone, Sparkles } from "lucide-react";
import ProblemForm from "../components/ProblemForm";
import HeroEnhanced from "../components/HeroEnhanced";
import { catalogueTools, coreTools, microSaas } from "../components/microSaas";

export default function Home() {
  return <main>
    <header className="top"><a className="brand" href="#top">ЭЙ АЙ, <em>БОЛЬНО</em></a><div className="topRight"><span>МИКРОИНСТРУМЕНТЫ / 14</span><a href="https://t.me/bloodaman" target="_blank" rel="noreferrer">TELEGRAM ↗</a></div></header>
    <section className="hero" id="top">
      <div className="knot"><div className="knotFallback"><i /><i /><i /><i /></div><HeroEnhanced /></div>
      <div className="heroCopy"><p className="eyebrow"><span /> Каталог микроинструментов для малого бизнеса</p><h1>Бизнесу не нужна<br />ещё одна система.<br /><em>Ему больно</em> терять<br />одно и то же.</h1><p className="heroText">Заявки тонут в чатах. Новичков учат по памяти. Смены передают на словах. Мы собираем заявки на микроинструменты, которые распутывают одну ручную операцию за раз.</p><a href="#form" className="button">Описать боль <ArrowDownRight size={18} /></a><a href="#details" className="buttonGhost">Смотреть каталог <ArrowDownRight size={18} /></a></div>
      <p className="heroFoot">СОБИРАЕМ ЗАЯВКИ НА РАЗРАБОТКУ<br />ОТВЕТИМ В ТЕЧЕНИЕ ДНЯ</p>
    </section>
    <section className="diagnosis"><p className="sectionNo">01 / ДИАГНОЗ</p><h2>Хаос не появляется<br />вдруг. Он <em>копится.</em></h2><div className="sceneGrid"><article><b>«Где была эта заявка?»</b><p>Клиент написал, менеджер ответил в личке, детали остались в голосовом — к вечеру никто не помнит, что обещали.</p></article><article><b>«Кто объяснит это новенькому?»</b><p>Сотрудник ушёл, инструкция ушла вместе с ним. Следующий человек снова учится на ошибках.</p></article><article><b>«А смене вообще передали?»</b><p>Незакрытая задача, остаток, конфликт с клиентом — всё существует, пока о нём не узнают слишком поздно.</p></article></div><p className="diagnosisEnd">Не надо внедрять монстра ради одной дырявой операции. Найдите свою боль — соберём для неё маленький, понятный инструмент.</p></section>
    <section className="solutions" id="solutions"><div className="solutionIntro"><p className="sectionNo">02 / ПЕРВЫЕ УЗЛЫ</p><h2>Начнём с того,<br />что <em>болит каждый день.</em></h2></div><div>{coreTools.map((tool) => <article className="solution" key={tool.id}><span>{tool.num}</span><div><p className="solutionName">{tool.name}</p><h3>{tool.short?.title}</h3><p>{tool.short?.text}</p><div className="solutionCtas"><a href="#form">Хочу разобрать этот процесс <ArrowUpRight size={16} /></a><a href={`#${tool.id}`}>Что внутри <ArrowDownRight size={16} /></a></div></div></article>)}</div></section>
    <section className="catalogue" id="catalogue"><div><p className="sectionNo">03 / В РАБОТЕ</p><h2>Другие боли тоже<br /><em>не обязаны жить</em><br />в таблицах.</h2><p className="catalogueHint">Каждая строка — ссылка на подробный разбор: как болит, что распутывает и кому подходит.</p></div><div className="catalogueList">{catalogueTools.map((tool) => <a href={`#${tool.id}`} key={tool.id}><span>{tool.num}</span>{tool.name}<small>Проверяем спрос <ArrowUpRight size={14} /></small></a>)}</div></section>
    <section className="details" id="details"><div className="detailsHead"><div><p className="sectionNo">04 / КАТАЛОГ В ДЕТАЛЯХ</p><h2>Четырнадцать узлов.<br />Каждый — <em>по-своему.</em></h2></div><p>Выше — вся карта инструментов. Ниже — подробный разбор каждого: как процесс выглядит сейчас, что инструмент должен распутать и кому это подходит. Это заявки на разработку, а не готовые сервисы: чем точнее описана боль, тем быстрее инструмент соберётся.</p></div><div className="detailsList">{microSaas.map((tool) => <article className="detail" id={tool.id} key={tool.id}><div className="detailSide"><span>{tool.num}</span><p className="detailName">{tool.name}</p><p className="detailStatus">{tool.core ? "Первый в очереди на разработку" : "Проверяем спрос"}</p></div><div><h3>{tool.title}</h3><p className="detailPain">{tool.pain}</p><ul className="detailSigns">{tool.signs.map((sign) => <li key={sign}>{sign}</li>)}</ul><p className="detailUnblock"><b>Что должен распутать. </b>{tool.unblock}</p><p className="detailAudience">Кому подходит: {tool.audience}</p><a className="detailCta" href="#form">Описать эту боль <ArrowUpRight size={16} /></a></div></article>)}</div></section>
    <section className="process"><p className="sectionNo">05 / БЕЗ МАГИИ</p><div className="processTitle"><h2>Не обещаем<br />«подключить завтра».<br /><em>Сначала поймём.</em></h2><p>Это не готовая коробка и не внедрение на полгода. Берём в разработку те процессы, которые повторяются и действительно мешают работать.</p></div><ol><li><span>1</span><b>Вы описываете одну боль</b><p>Не «нужна автоматизация», а «заявка теряется между Telegram и менеджером».</p></li><li><span>2</span><b>Мы отвечаем в течение дня</b><p>Уточняем, где процесс ломается, кто участвует и какой результат нужен.</p></li><li><span>3</span><b>Собираем сценарий пилота</b><p>Вы понимаете, что будет проверяться, какие данные нужны и что не входит в первую версию.</p></li><li><span>4</span><b>Берём приоритетные запросы в работу</b><p>Без обещаний, которые нельзя выполнить. Сначала условия, потом сроки.</p></li></ol></section>
    <section className="formSection" id="form"><div className="formLead"><p className="sectionNo">06 / ВАША ОЧЕРЕДЬ</p><h2>Назовите одну<br />операцию, от которой<br /><em>уже больно.</em></h2><p>Не будем продавать систему на полгода внедрения. Сначала поймём, можно ли распутать именно ваш узел.</p><a className="contact" href="tel:+79037275131"><Phone size={18} /> +7 903 727-51-31</a><a className="contact" href="https://t.me/bloodaman" target="_blank" rel="noreferrer"><Sparkles size={18} /> @bloodaman в Telegram</a></div><ProblemForm /></section>
    <section className="faq"><p className="sectionNo">07 / БЕЗ МЕЛКОГО ШРИФТА</p><details><summary>Это уже готовые сервисы?<span>+</span></summary><p>Нет. Сейчас мы собираем заявки, чтобы брать в разработку самые повторяющиеся и дорогие для бизнеса процессы.</p></details><details><summary>Вы подключаетесь к CRM, 1С или Telegram?<span>+</span></summary><p>Возможность и способ интеграции обсуждаем после разбора процесса. Не обещаем готовое подключение до технической оценки.</p></details><details><summary>Можно прислать базу клиентов или документы?<span>+</span></summary><p>Не через эту форму. На первом шаге достаточно описать процесс без чувствительных данных.</p></details><details><summary>Как быстро вы отвечаете?<span>+</span></summary><p>В течение дня.</p></details></section>
    <footer><a className="brand" href="#top">ЭЙ АЙ, <em>БОЛЬНО</em></a><p>Одна ручная операция — за раз.</p><a href="tel:+79037275131">+7 903 727-51-31</a></footer>
  </main>;
}
